spring:
  application:
    name: service4
server:
  port: 8040

eureka:
  instance:
    prefer-ip-address: true
    metadata-map:
      serviceName: service4
      version: v2.0.0
      serviceDepencies:
        service3: v2.0.0
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${MCLUSTER_IP}:${MCLUSTER_PORT}/eureka
